# on: [push]
on:
  pull_request:
name: Analysis Shifleft
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test Analysis Action
        uses: ItBeginsWCC/shiftleft-docker-analysis@v11.0.3
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          language: 'go'
          go-version: '1.17'
          app-name: 'shiftleft-go-demo'
          app-path: './...'

  Build-Rules:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: test-action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Break The Build Analysis Action
        uses: ItBeginsWCC/Break-The-Build@v3.4
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          app-name: 'shiftleft-go-demo'
          break-the-build: 'Y'
          github-token: ${{ secrets.GITHUB_TOKEN }}
